# Generated by Django 5.2.5 on 2025-08-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiposriscos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tiporisco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposriscos.tiporisco')),
            ],
            options={
                'db_table': 'risco',
            },
        ),
    ]
